version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
#      - ./my.cnf:/etc/mysql/my.cnf
    restart: always
    ports:
      - '9001:3306'
    environment:
      MYSQL_ROOT_PASSWORD: happy2code
      MYSQL_DATABASE: wp277
      MYSQL_USER: root
      MYSQL_PASSWORD: happy2code
    networks:
      - wpsite

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '9999:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: happy2code 
    networks:
      - wpsite

  wordpress:
    depends_on:
      - db
    image: wordpress:5.2.2-php7.1-apache
    ports:
      - "9000:80"
    restart: always
    environment:
      WORDPRESS_DB_NAME: wp277
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: happy2code
    volumes:
      - ./:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - wpsite

networks:
  wpsite:

volumes:
  db_data:
